name: Wake up call
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *' # Top of every hour

jobs:
  wake-up-call:
    name: wake up call
    runs-on: ubuntu-latest

    steps:
      - name: Make a Twilio call through curl
        uses: wei/curl@v1.1.1
        with:
          args: -X POST  https://api.twilio.com/2010-04-01/Accounts/${{ secrets.ACCOUNT_ID }}/Calls.json --data-urlencode "To=${{ secrets.TO_NUMBER }}" --data-urlencode "From=${{ secrets.FROM_NUMBER }}" --data-urlencode "Url=https://handler.twilio.com/twiml/${{ secrets.TWIML_ID }}" -u ' ${{ secrets.ACCOUNT_ID }}:${{ secrets.TOKEN }}'
