name: Wake up call
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *' # every day at 9 am UTC
      
jobs:
  wake-up-call:
    name: wake up call
    runs-on: ubuntu-latest

    steps:
      - name: Twilio Voice Call
        # You may pin to the exact commit or the version.
        # uses: fabasoad/twilio-voice-call-action@3fcb40374f6352418ec45bd14c35823a021219aa
        uses: fabasoad/twilio-voice-call-action@v1.1.2
        with:
          # Twilio Account SID.
          twilio_account_sid: ${{ secrets.ACCOUNT_ID }}
          # Twilio Auth token.
          twilio_auth_token: ${{ secrets.TOKEN }}
          # Text that will be send by voice call.
          text: "This is your wake up call. Have a great day."
          # Phone number in your Twilio account to send the voice call from.
          from: ${{ secrets.FROM_NUMBER }}
          # Phone number to send the voice call to.
          to: ${{ secrets.TO_NUMBER }}
